"""add created_at to ratings

Revision ID: 1a88bfe18490
Revises: b71394c7137a
Create Date: 2025-02-03 15:08:16.912678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a88bfe18490'
down_revision: Union[str, None] = 'b71394c7137a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert published_date from VARCHAR to DATE using explicit cast
    op.execute('ALTER TABLE papers ALTER COLUMN published_date TYPE DATE USING published_date::date')
    
    # Create index on published_date
    op.create_index(op.f('ix_papers_published_date'), 'papers', ['published_date'], unique=False)
    
    # Drop unused created_at columns
    op.drop_column('papers', 'created_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('papers', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_papers_published_date'), table_name='papers')
    op.alter_column('papers', 'published_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
